---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonjour-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonjour
  template:
    metadata:
      labels:
        app: bonjour
      annotations:
        prometheus.io/port: '9394'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: main
        image: jmtrusona/bonjour-service:0.0.0
        imagePullPolicy: "Always"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        envFrom:
        - secretRef:
            name: bonjour-secrets
      - name: prometheus-exporter
        image: jmtrusona/bonjour-service:0.0.0
        imagePullPolicy: "Always"
        command: ["bundle", "exec", "prometheus_exporter" ]
        args:
          - -v
        ports:
        - name: http-metrics
          containerPort: 9394
          protocol: TCP