apiVersion: v1
kind: Service
metadata:
  name: bonjour-service
spec:
  selector:
    app: bonjour
  type: NodePort
  ports:
  - name: app
    protocol: TCP
    port: 8080
  - name: http-metrics
    protocol: TCP
    port: 9394