
default: &default
  adapter: postgresql
  encoding: unicode
  sslmode: require
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trusona

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>